# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLbl = QtWidgets.QLabel(self.centralwidget)
        self.nameLbl.setGeometry(QtCore.QRect(0, 5, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLbl.setFont(font)
        self.nameLbl.setObjectName("nameLbl")
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameLineEdit.setGeometry(QtCore.QRect(160, 5, 460, 30))
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.browserBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browserBtn.setGeometry(QtCore.QRect(630, 5, 121, 28))
        self.browserBtn.setObjectName("browserBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.browserBtn.clicked.connect(self.browseFile)

    def browseFile(self):
        fileName = QFileDialog.getOpenFileNames(None, 'Open File', 'c:\\Users\Serfeg\Documents\GitHub\KMCRODiploma')[0]
        str1 = fileName[0].split("/")
        print(str1[-1])
        self.fileNameLineEdit.setText(fileName[0])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KMCRO"))
        self.nameLbl.setText(_translate("MainWindow", "Путь файла"))
        self.browserBtn.setText(_translate("MainWindow", "Обзор"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
