# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.clusterFile = 'Если ты это видишь, то значит значение пусто'
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLbl = QtWidgets.QLabel(self.centralwidget)
        self.nameLbl.setGeometry(QtCore.QRect(10, 5, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLbl.setFont(font)
        self.nameLbl.setObjectName("nameLbl")
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileNameLineEdit.setGeometry(QtCore.QRect(160, 5, 460, 30))
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.browserBtn = QtWidgets.QPushButton(self.centralwidget)
        self.browserBtn.setGeometry(QtCore.QRect(630, 5, 161, 30))
        self.browserBtn.setObjectName("browserBtn")
        self.euclidDistRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.euclidDistRadio.setGeometry(QtCore.QRect(160, 50, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.euclidDistRadio.setFont(font)
        self.euclidDistRadio.setObjectName("euclidDistRadio")
        self.kMeansLbl = QtWidgets.QLabel(self.centralwidget)
        self.kMeansLbl.setGeometry(QtCore.QRect(10, 43, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kMeansLbl.setFont(font)
        self.kMeansLbl.setObjectName("kMeansLbl")
        self.cosineSimRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.cosineSimRadio.setGeometry(QtCore.QRect(300, 50, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cosineSimRadio.setFont(font)
        self.cosineSimRadio.setObjectName("cosineSimRadio")
        self.outputEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.outputEdit.setGeometry(QtCore.QRect(10, 80, 781, 321))
        self.outputEdit.setObjectName("outputEdit")
        self.performBtn = QtWidgets.QPushButton(self.centralwidget)
        self.performBtn.setGeometry(QtCore.QRect(10, 410, 161, 30))
        self.performBtn.setObjectName("performBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.browserBtn.clicked.connect(self.browseFile)

    def browseFile(self):
        fileName = QFileDialog.getOpenFileNames(None, 'Open File', './')[0]
        if fileName:
            self.clusterFile = fileName[0].split("/")[-1]
            self.fileNameLineEdit.setText(fileName[0])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KMCRO"))
        self.nameLbl.setText(_translate("MainWindow", "Название файла"))
        self.browserBtn.setText(_translate("MainWindow", "Обзор"))
        self.euclidDistRadio.setText(_translate("MainWindow", "Euclidean Distance"))
        self.kMeansLbl.setText(_translate("MainWindow", "K-means"))
        self.cosineSimRadio.setText(_translate("MainWindow", "Cosine Similarity"))
        self.performBtn.setText(_translate("MainWindow", "Обзор"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
